### PR TITLE
comment out unit test

### PR DESCRIPTION
**Pull request by tomchavakis**

### CODE REVIEW

**Comment by tomchavakis** [comment]
Hi @Lexy2,

I need your help regarding an issue that came up after merging the PR in master.
Locally, the Tests are passing ( the famous: it runs in my machine ), but failing on the github & appveyor actions.
The Test GetNugetInformationAsync_Should_Resolve_Missing_NuSpec_File makes use of the "new" code and I think that the problem is a matter of multithreading issue. 
Related issue (https://github.com/tomchavakis/nuget-license/pull/100).
If I am commenting on this test then a lot of other tests are failing.
Can you please validate that the tests are passing in your machine and help me to find out the root cause of this issue ?
Thanks

**Comment by Lexy2** [comment]
Hi @tomchavakis ,

I saw this test and I have no idea why it is failing. 
My only idea is that GitHub runners do not allow access to the internet from the test environment, but I have not seen any confirmation of that behaviour.
I'll do more extensive testing next week.

**Comment by Lexy2** [comment]
Well, my current idea is that GitHub actions run on different runners hosting different OSes. These OSes handle dotnet web requests differently. Some of them are case-sensitive, some of them are case-insensitive. 

I guess one could open an issue at https://github.com/actions/runner repo.

**Comment by tomchavakis** [comment]
Hi @Lexy2,

I've integrated also it with appveyor and is failing exactly at the same issues, so I am not sure if it's a problem with the github action. I have tried to test it through the new VS2022 feature of remote testing https://docs.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022 on Linux through a docker container and WSL2 but I haven't completed the integration yet.

**Pull request closed without merging**
