### PR TITLE
adds optional projectUrls and error ignoring (V3.0.0 alpha)

### PR DESCRIPTION
**Pull request by jdrst**
Hi,

here's an attempt at adding both error ignoring and the possibility to output project urls.

As per [#127](https://github.com/tomchavakis/nuget-license/issues/127#issuecomment-1240933105) i tried to be as unintrusive as possible and adhere to the structure. Still, I took the liberty of renaming some things and changing a deprecated api call.

If there are suggestions or problems or i overlooked/forgot something, please let me know. You also have edit rights.

### CODE REVIEW

**Comment by sensslen** [comment]
First of all: Thank you very much for your contribution. I do really appreciate!

However I do have some concerns about this Pull Requst.

1. It contains two features. Would you mind seperating them into two Pull Requests? It makes things easyer to review.
2. I'd much rather include the project url in every json output. Since it is ment to be processed further the additional information can be ignored very easily. In this spirit I think it would be great to just add a new output type which prints the package information in tabular form including the project url.
3. Would you mind motivating the second feature you implemented? I don't see why one would like to ignore the errors. If you're just interrested in all licenses used, you could as well omit the `-a / --allowed-license-types` parameter which essentially skips validation and just prints licenses.

Thanks for clarification!

**Comment by svenclaesson** [comment]
I agree that the early exit is a bit of a problem. 
Omitting `-a` does not skip validation and when there is an error, one missing license, none of the valid packages are listed. 

I'd rather have an option `-onlyerr` that works just like it does today in alpha for those that any missing license is a showstopper.
I would preferer the new default to have everything included in the same output like this,

```
[
  {
    "PackageId": "Human Web Planner",
    "PackageVersion": "7.2.6",
    "License": "I\u0027ll calculate the virtual XML firewall, that should firewall the XML firewall!",
    "LicenseInformationOrigin": 0,
    "ProjectUrl": "http://santino.biz"
  },
  {
    "PackageId": "Dynamic Data Manager",
    "PackageVersion": "9.7.7",
    "License": "**No license information found**",
    "LicenseInformationOrigin": 0,
    "ProjectUrl": "http://julian.name"
  }
]
```

**Comment by jdrst** [comment]
First of all: i'm very open to changing all of this. I'd rather discuss beforehand though :D

> It contains two features. Would you mind seperating them into two Pull Requests? It makes things easyer to review.

I sure can. If it's just about reviewing though: one of the changes (-noerr) is a single commit with <10 lines added/changed. If you still want me to separate that, just let me know. 
Since we're already dicussing here though and things might change, i'll let this stand until we hopefully reach an agreement on what and how.

> I'd much rather include the project url in every json output. Since it is ment to be processed further the additional information can be ignored very easily. In this spirit I think it would be great to just add a new output type which prints the package information in tabular form including the project url.

That works for me too. But in my personal opinion i would expect the tool to give me the same output in json and tabular form given the same input. That would mean either adding the project urls in on a parameter basis (as in this pr) or excluding them on a parameter basis (meaning the default output includes urls for both json and tabular form). What do you think about that?

> Would you mind motivating the second feature you implemented? I don't see why one would like to ignore the errors. If you're just interrested in all licenses used, you could as well omit the -a / --allowed-license-types parameter which essentially skips validation and just prints licenses.

As @svenclaesson already said, it doesn't skip validation. Imagine a (or even several) big codebase(s) with an internal nugetfeed and lots of internal packages that don't necessary have license information. If i understand correctly: with the current state of the alpha i'd have to ignore every single one of these packages in every single codebase per hand, in a json file. And adding a single new reference without changing/maintaining the corresponding json file currently means i get no output at all. Just the single error.
While part of this can be mitigated by e.g. adding regexes in the json i'd still have to either have a central file or a file per project. This is part of the reason for my proposal. I personally like this idea much better though:

> I'd rather have an option -onlyerr that works just like it does today in alpha for those where any missing license is a showstopper.

In light of this problem i'd also much rather define a reusable ci/build step that doesn't need outside input. That's why i was planning on also adding (back) regex ignoring (both in the json and directly via cli) in another pr. Any input on that?

**Comment by sensslen** [comment]
Hi @jdrst and @svenclaesson 

thanks a lot for your inputs. I can see why you want to ignore license errors. However if I understand your implementation correctly after the change the tool does something similar to what it does now - it just ignores the errors (which one might be interrested in). When thinking about this during the week I think something similar to what @svenclaesson suggested is much better suited to work. How about combining the Output in the following manner:

`
[
{
"PackageId": "Human Web Planner",
"PackageVersion": "7.2.6",
"License": "I\u0027ll calculate the virtual XML firewall, that should firewall the XML firewall!",
"LicenseInformationOrigin": 0,
"ProjectUrl": "http://santino.biz"
},
{
"PackageId": "Dynamic Data Manager",
"PackageVersion": "9.7.7",
"License": "some not supported license",
"LicenseInformationOrigin": 0,
"ProjectUrl": "http://julian.name",
"ValidationError":" License some not supported license not found in list of supported licenses",
"ErrorContext":"C:\some\path"
},
{
"PackageId": "Dynamic Data Manager",
"PackageVersion": "9.7.7",
"LicenseInformationOrigin": 0,
"ProjectUrl": "http://julian.name",
"ValidationError":"No license information found",
"ErrorContext":"C:\some\path"
}
]
`

This way we combine the information of the errors into the validation results which improves the output of the tool. Then we could add the flag `-onlyerr` to skip all valid licenses in order to print only invalid results.

Regarding the inclusion of the project url: I'd make things very easy here. Since we're still in alpha (which means the interface might well change), I'd say we just include this information alsways. Do you have any objections @tomchavakis?

Concerning the Seperation of the two features: I think this really makes sense - even more so if the two features get totally seperate lifespans since I think the `-onlyerr` flag needs an api spec before implementing it.

**Comment by sensslen** [comment]
I just created a PR that implements my draft above. With this all validated pakcages are printed (provided there was not any severe error - like failing web requests). I think this should resolve the issues this PR resolves and improve upon it, as the result of each package validation is printed. See #155

**Comment by sensslen** [comment]
Closing in favour of #155

**Comment by jdrst** [comment]
Works for me! Sorry for the late response, i was preoccupied with other things.

**Pull request closed without merging**
