### PR TITLE
Output a markdown file

### PR DESCRIPTION
**Pull request by elangelo**

### CODE REVIEW

**Comment by elangelo** [comment]
I did a quick try if i could easily output markdown with this. The table that was written was actually already very close so i basically copied that base method and passed in as markdown. If you prefer that i completely replace the asstringtable method with this new one i can do that...

**Comment by tomchavakis** [comment]
Hi @elangelo ,

I would like to thank you for your contribution. 
Regarding the asstringtable method, I think that it's better to have it in both versions as you have it in your PR.

**Comment by elangelo** [comment]
Hi @tomchavakis any chance of completing this? i'm now using a custom build in our process to push out these md files, it would really like to start using the official distribution as fast as possible.

**Comment by tomchavakis** [comment]
Hi @elangelo ,

You can find the release with your contribution at the following link: 
https://github.com/tomchavakis/nuget-license/releases/tag/v2.3.11

Thank you for your contribution

**Pull request merged**
