### PR TITLE
Some misc fixes and additions

### PR DESCRIPTION
**Pull request by bmcdavid**
bug fixes
added url license protocol/case insenstive comparer
added fluent assertions

### CODE REVIEW

**Comment by tomchavakis** [comment]
Hi @bmcdavid ,

Thanks again for your support!!!

**Comment by bmcdavid** [comment]
You’re welcome! There may also be an issue with the .sln parser I picked. Debating whether or not to just write one from scratch for this project. In Linux we don’t get any results compared to windows for those files.

**Comment by tomchavakis** [comment]
Could you please elaborate more on the .sln parser issue?
Moreover, I will try to resolve some issues with Unit Tests for Linux in order to use travis for building/testing and release process.

**Comment by bmcdavid** [comment]
When we ran on Linux with -i VSSolutionFile.sln and -l Verbose logging and only a few packages were picked up. I think perhaps that many csproj files in the solution were missed.  Maybe it’s a file name casing issue where Linux is sensitive to that, but didn’t have a chance to look closely at the time.

**Comment by tomchavakis** [comment]
As I can see you have fixed the issue with the Linux tests!!!
I can confirm it because I've checked tests to my local environment (Ubuntu) and it's fine.
Thanks again for your contribution.
When you feel ready just merge the PR.

I will continue with github actions in order to have an auto release version (github/nuget).

**Comment by bmcdavid** [comment]
You’re welcome. I tried to merge but don’t have permission for that. 

Issue with Linux and Path.Combine is it doesn’t change the sln Windows path automatically, this a new extension to help.

**Comment by tomchavakis** [comment]
I have added you as contributor to the project right now, so you must have the appropriate permissions in order to merge this PR.

**Comment by bmcdavid** [comment]
Awesome thanks!

**Pull request merged**
