### PR TITLE
Use local cache to retreive package information

### PR DESCRIPTION
**Pull request by sensslen**
This PR superseeds #145 by properly structuring the code and also adding unit tests

### CODE REVIEW

**Comment by svenclaesson** [comment]
PackageVersion is empty now everywhere?

**Comment by sensslen** [comment]
> PackageVersion is empty now everywhere?

Thanks a lot for catching this - I just missed this!!!
I just corrected this bug....

**Comment by svenclaesson** [comment]
I'm getting searchMetadata.LicenceMetadata = null on CachingPackageMetadataResource line46 for some packages like CsvHelper 2.16.3 but I haven't investigated further.

Also, I don't think you intended to check in launchSettings.json...

Thanks for this!

**Comment by sensslen** [comment]
Digging into this: It was a problem in the wrapper. I fixed this as well.

**Review by svenclaesson — APPROVED** [review]
Looks good to me

**Pull request merged**
