### PR TITLE
Added Regex support for filtering out unwanted packages

### PR DESCRIPTION
**Pull request by actuallyrob**

### CODE REVIEW

**Comment by tomchavakis** [comment]
Hi @actuallyrob,

Thank's for this PR. 
It's a nice addition!!

**Comment by actuallyrob** [comment]
😄 Glad that you like it!

When are you planning the next release of this package?

**Comment by tomchavakis** [comment]
Hi @actuallyrob,
today afternoon or during the weekend.
Is that ok with you? Do you need this functionality earlier?

**Comment by actuallyrob** [comment]
@tomchavakis That's okay!
I am currently packing my own fork in my CI/CD, so I'm able to utilize my added functionality.
It would be cleaner to simply install it from nuget, that's why I am asking 😃

**Comment by tomchavakis** [comment]
@actuallyrob, v2.2.9 just released.

**Pull request merged**
