### PR TITLE
Implement core functionality using nuget commands and msbuild

### PR DESCRIPTION
**Pull request by sensslen**
This pull request essentially is a completely new implementation of the core functionality of the project.

It does address various issues:
- #93 (not tested, but since the new implementation uses msbuild this should work)
- #80 
- #51 (main focus of development)
- #29 (not tested, but since the new implementation uses msbuild this should work)

Further this PR also allows to validate against the new nuget syntax which is not using license url but license metadata instead.

Note: This PR does not intend to implement all of the functionality that was previously there.

### CODE REVIEW

**Comment by tomchavakis** [comment]
Hi @sensslen,

I am sorry for the late response. 
Thank you for your PR. It's a really nice approach and well structured.
I am not really sure if it's a good idea to merge it on master because we need to deprecate several features or enough time to make it backwards compatible.
I was thinking to create a new version of the tool with your approach and deprecating this version.
Would you like to have a conversation about it (my email is on the github profile)?

**Comment by kl1mm** [comment]
When will this feature be available? We are waiting eagerly :)

**Comment by sensslen** [comment]
The feature is available in the version3.0.0 alpha branch (https://github.com/tomchavakis/nuget-license/tree/v3.0.0-alpha). We're using this branch for some month's now - working very well....

**Comment by kl1mm** [comment]
Thank you, is it possible to download the bits via a feed?
We use the tool in the CI on AzureDevOps and install it via dotnet tool install from Nuget. 
Locally the 3.0.0 works for us, but in the CI we unfortunately don't have access to the binaries.

Best regards

**Comment by sensslen** [comment]
@tomchavakis would you be able to help me out in implementing the necessary steps to publish the app in a form that makes it installable via dotnet?

**Comment by tomchavakis** [comment]
Hi @sensslen,

For sure, I will come in contact with you.

**Comment by sensslen** [comment]
@kl1mm please find the release here: https://www.nuget.org/packages/dotnet-project-licenses/3.0.0-alpha.1

**Pull request merged**
